version: '3.10'
services:
  ####################
  app:
    build: .
    command: sh -c "alembic upgrade head && 
                    uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000
    depends_on:
      - database
    networks:
      - app_network
    environment:
      - DB_NAME = ${DATABASE_NAME}
      - DB_USER = ${DATABASE_USER}
      - DB_PASSWORD = ${DATABASE_PASSWORD}
      - DB_PORT = ${DATABASE_PORT}
      - DB_HOST = ${DATABASE_HOST}
  ####################
  database:
    container_name: database_beewise
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - app_network
    ports:
      - "5432"
volumes:
  postgres_data:
networks:
  app_network:
