version: '3.10'
services:
  ####################
  # backend:
  #   build: ./app
  #   command: "gunicorn store.wsgi:application --bind 0.0.0.0:8000"
  #   restart: always
  #   env_file:
  #     - ./app/.env
  #   volumes:
  #     - static_volume:/home/app/web/backend_static
  #     - media_volume:/home/app/web/backend_media
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - app_network
  #   depends_on:
  #     - database
  #     - redis
  ####################
  database:
    container_name: database_beewise
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - app_network
  ##################
  # nginx:
  #   image: 'jc21/nginx-proxy-manager:latest'
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #     - '81:81'
  #     - '443:443'
  #   volumes:
  #     - ./data:/data
  #     - ./letsencrypt:/etc/letsencrypt
  #     - static_volume:/home/app/web/backend_static
  #     - media_volume:/home/app/web/backend_media
  #   networks:
  #     - app_network

volumes:
  static_volume:
  media_volume:
  postgres_data:
networks:
  app_network:
