version: '3.10'
services:
  ####################
  app:
    build: .
    command: sh -c "alembic upgrade head && 
                    uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000
    depends_on:
      - database
    networks:
      - app_network
  ####################
  database:
    container_name: database_beewise
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - app_network
    ports:
      - "5432"
  ##################
  # nginx:
  #   image: 'jc21/nginx-proxy-manager:latest'
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #     - '81:81'
  #     - '443:443'
  #   volumes:
  #     - ./data:/data
  #     - ./letsencrypt:/etc/letsencrypt
  #     - static_volume:/home/app/web/backend_static
  #     - media_volume:/home/app/web/backend_media
  #   networks:
  #     - app_network
volumes:
  postgres_data:
networks:
  app_network:
