"""empty message

Revision ID: 326463a61630
Revises: d03302f56015
Create Date: 2023-10-18 19:59:16.344698

"""


# revision identifiers, used by Alembic.
revision = "326463a61630"
down_revision = "d03302f56015"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
