"""empty message

Revision ID: 4d13ee33fc6f
Revises: 326463a61630
Create Date: 2023-10-18 22:50:32.790150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d13ee33fc6f"
down_revision = "326463a61630"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quizquestionmodel", "value", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quizquestionmodel", "value", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
