"""empty message

Revision ID: d03302f56015
Revises: 837915e21f12
Create Date: 2023-10-18 19:58:19.770739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d03302f56015"
down_revision = "837915e21f12"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("quizquestionmodel", sa.Column("value", sa.Integer(), nullable=False))
    op.add_column(
        "quizquestionmodel",
        sa.Column(
            "airdate",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "quizquestionmodel", sa.Column("category_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "quizquestionmodel", sa.Column("game_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "quizquestionmodel", sa.Column("invalid_count", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quizquestionmodel", "invalid_count")
    op.drop_column("quizquestionmodel", "game_id")
    op.drop_column("quizquestionmodel", "category_id")
    op.drop_column("quizquestionmodel", "airdate")
    op.drop_column("quizquestionmodel", "value")
    # ### end Alembic commands ###
